[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["ats"]

[project]
name = "ats"
version = "0.1.0"
description = "Agentic table search library"
requires-python = ">=3.12"
dependencies = []
